[target.powerpc-unknown-linux-gnu]
linker = "powerpc64-linux-gnu-gcc"
ar = "powerpc64-linux-gnu-gcc-ar"
rustflags = [
    "-C", "link-args=-nostdlib -ffreestanding -fPIC -mbig-endian",
    "-C", "target-feature=+crt-static",
]
